CREATE USER ORCLSTUDY
IDENTIFIED BY ORACLE;

GRANT CREATE SESSION TO ORCLSTUDY;

ALTER USER ORCLSTUDY
IDENTIFIED BY ORCL;

DROP USER ORCLSTUDY;

DROP USER ORCLSTUDY CASCADE;

CREATE USER ORCLSTUDY
IDENTIFIED BY ORACLE;

GRANT CREATE SESSION, RESOURCE, CREATE TABLE TO ORCLSTUDY;

CREATE ROLE ROLESTUDY;

GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SYNONYM
TO ROLESTUDY;

GRANT ROLESTUDY TO ORCLSTUDY;


-- P.416 Q1)
CREATE USER PREV_HW
IDENTIFIED BY ORCL;

GRANT CREATE SESSION TO PREV_HW;